// ignore_for_file: non_constant_identifier_names, camel_case_types, file_namesimport, file_names, unnecessary_null_comparison,prefer_null_aware_operators

// WARNING: This code is auto-generated by Supadart.
// WARNING: Modifications may be overwritten. Please make changes in the SupaDart configuration.

// SDK
import 'package:supabase_flutter/supabase_flutter.dart';

import 'package:geobase/geobase.dart';

// No Intl package needed
// No Dart Convert needed
// No JSONB Model imports needed
// Supadart Class
abstract class SupadartClass<T> {
  static Map<String, dynamic> insert(Map<String, dynamic> data) {
    throw UnimplementedError();
  }

  static Map<String, dynamic> update(Map<String, dynamic> data) {
    throw UnimplementedError();
  }

  factory SupadartClass.fromJson(Map<String, dynamic> json) {
    throw UnimplementedError();
  }

  static converter(List<Map<String, dynamic>> data) {
    throw UnimplementedError();
  }

  static converterSingle(Map<String, dynamic> data) {
    throw UnimplementedError();
  }
}

// Supabase Client Extension
extension SupadartClient on SupabaseClient {
  SupabaseQueryBuilder get pin => from('pin');
  SupabaseQueryBuilder get pin_source => from('pin_source');
  SupabaseQueryBuilder get source_documentaire => from('source_documentaire');
  SupabaseQueryBuilder get membre_equipe => from('membre_equipe');
  SupabaseQueryBuilder get trace_validation => from('trace_validation');
  SupabaseQueryBuilder get epoque => from('epoque');
  SupabaseQueryBuilder get categorie => from('categorie');
  SupabaseQueryBuilder get pin_epoque => from('pin_epoque');
}

// Supabase Storage Client Extension
extension SupadartStorageClient on SupabaseStorageClient {}

// Enums
enum PROVENANCE_PIN { editorial, communautaire }

enum STATUT_PIN { brouillon, en_revue, valide, publie, retire }

enum ROLE_EQUIPE { editeur, validateur, moderateur }

// Utils
class Pin implements SupadartClass<Pin> {
  final String id;
  final String slug;
  final String titre;
  final PROVENANCE_PIN provenance;
  final String categorieId;
  final Map<String, dynamic> contenuNarratif;
  final STATUT_PIN statut;
  final Geometry? localisation;
  final DateTime createdAt;
  final DateTime updatedAt;

  const Pin({
    required this.id,
    required this.slug,
    required this.titre,
    required this.provenance,
    required this.categorieId,
    required this.contenuNarratif,
    required this.statut,
    this.localisation,
    required this.createdAt,
    required this.updatedAt,
  });

  static String get table_name => 'pin';
  static String get c_id => 'id';
  static String get c_slug => 'slug';
  static String get c_titre => 'titre';
  static String get c_provenance => 'provenance';
  static String get c_categorieId => 'categorie_id';
  static String get c_contenuNarratif => 'contenu_narratif';
  static String get c_statut => 'statut';
  static String get c_localisation => 'localisation';
  static String get c_createdAt => 'created_at';
  static String get c_updatedAt => 'updated_at';

  static List<Pin> converter(List<Map<String, dynamic>> data) {
    return data.map(Pin.fromJson).toList();
  }

  static Pin converterSingle(Map<String, dynamic> data) {
    return Pin.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? slug,
    String? titre,
    PROVENANCE_PIN? provenance,
    String? categorieId,
    Map<String, dynamic>? contenuNarratif,
    STATUT_PIN? statut,
    Geometry? localisation,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (slug != null) 'slug': slug,
      if (titre != null) 'titre': titre,
      if (provenance != null)
        'provenance': provenance.toString().split('.').last,
      if (categorieId != null) 'categorie_id': categorieId,
      if (contenuNarratif != null) 'contenu_narratif': contenuNarratif,
      if (statut != null) 'statut': statut.toString().split('.').last,
      if (localisation != null)
        'localisation': localisation.toBytesHex(format: WKB.geometryExtended),
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
      if (updatedAt != null) 'updated_at': updatedAt.toUtc().toIso8601String(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    required String slug,
    required String titre,
    PROVENANCE_PIN? provenance,
    required String categorieId,
    required Map<String, dynamic> contenuNarratif,
    STATUT_PIN? statut,
    Geometry? localisation,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return _generateMap(
      id: id,
      slug: slug,
      titre: titre,
      provenance: provenance,
      categorieId: categorieId,
      contenuNarratif: contenuNarratif,
      statut: statut,
      localisation: localisation,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? slug,
    String? titre,
    PROVENANCE_PIN? provenance,
    String? categorieId,
    Map<String, dynamic>? contenuNarratif,
    STATUT_PIN? statut,
    Geometry? localisation,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return _generateMap(
      id: id,
      slug: slug,
      titre: titre,
      provenance: provenance,
      categorieId: categorieId,
      contenuNarratif: contenuNarratif,
      statut: statut,
      localisation: localisation,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }

  factory Pin.fromJson(Map<String, dynamic> jsonn) {
    return Pin(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      slug: jsonn['slug'] != null ? jsonn['slug'].toString() : '',
      titre: jsonn['titre'] != null ? jsonn['titre'].toString() : '',
      provenance: jsonn['provenance'] != null
          ? PROVENANCE_PIN.values.byName(jsonn['provenance'].toString())
          : PROVENANCE_PIN.values.first,
      categorieId: jsonn['categorie_id'] != null
          ? jsonn['categorie_id'].toString()
          : '',
      contenuNarratif: jsonn['contenu_narratif'] != null
          ? jsonn['contenu_narratif'] as Map<String, dynamic>
          : <String, dynamic>{},
      statut: jsonn['statut'] != null
          ? STATUT_PIN.values.byName(jsonn['statut'].toString())
          : STATUT_PIN.values.first,
      localisation: jsonn['localisation'] != null
          ? GeometryBuilder.decodeHex(
              jsonn['localisation'].toString(),
              format: WKB.geometryExtended,
            )
          : null,
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
      updatedAt: jsonn['updated_at'] != null
          ? DateTime.parse(jsonn['updated_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
    );
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      slug: slug,
      titre: titre,
      provenance: provenance,
      categorieId: categorieId,
      contenuNarratif: contenuNarratif,
      statut: statut,
      localisation: localisation,
      createdAt: createdAt,
      updatedAt: updatedAt,
    );
  }
}

class PinSource implements SupadartClass<PinSource> {
  final String pinId;
  final String sourceId;

  const PinSource({required this.pinId, required this.sourceId});

  static String get table_name => 'pin_source';
  static String get c_pinId => 'pin_id';
  static String get c_sourceId => 'source_id';

  static List<PinSource> converter(List<Map<String, dynamic>> data) {
    return data.map(PinSource.fromJson).toList();
  }

  static PinSource converterSingle(Map<String, dynamic> data) {
    return PinSource.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({String? pinId, String? sourceId}) {
    return {
      if (pinId != null) 'pin_id': pinId,
      if (sourceId != null) 'source_id': sourceId,
    };
  }

  static Map<String, dynamic> insert({String? pinId, String? sourceId}) {
    return _generateMap(pinId: pinId, sourceId: sourceId);
  }

  static Map<String, dynamic> update({String? pinId, String? sourceId}) {
    return _generateMap(pinId: pinId, sourceId: sourceId);
  }

  factory PinSource.fromJson(Map<String, dynamic> jsonn) {
    return PinSource(
      pinId: jsonn['pin_id'] != null ? jsonn['pin_id'].toString() : '',
      sourceId: jsonn['source_id'] != null ? jsonn['source_id'].toString() : '',
    );
  }

  Map<String, dynamic> toJson() {
    return _generateMap(pinId: pinId, sourceId: sourceId);
  }
}

class SourceDocumentaire implements SupadartClass<SourceDocumentaire> {
  final String id;
  final String slug;
  final String type;
  final String reference;
  final String credit;
  final String? lien;
  final String? description;
  final DateTime createdAt;

  const SourceDocumentaire({
    required this.id,
    required this.slug,
    required this.type,
    required this.reference,
    required this.credit,
    this.lien,
    this.description,
    required this.createdAt,
  });

  static String get table_name => 'source_documentaire';
  static String get c_id => 'id';
  static String get c_slug => 'slug';
  static String get c_type => 'type';
  static String get c_reference => 'reference';
  static String get c_credit => 'credit';
  static String get c_lien => 'lien';
  static String get c_description => 'description';
  static String get c_createdAt => 'created_at';

  static List<SourceDocumentaire> converter(List<Map<String, dynamic>> data) {
    return data.map(SourceDocumentaire.fromJson).toList();
  }

  static SourceDocumentaire converterSingle(Map<String, dynamic> data) {
    return SourceDocumentaire.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? slug,
    String? type,
    String? reference,
    String? credit,
    String? lien,
    String? description,
    DateTime? createdAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (slug != null) 'slug': slug,
      if (type != null) 'type': type,
      if (reference != null) 'reference': reference,
      if (credit != null) 'credit': credit,
      if (lien != null) 'lien': lien,
      if (description != null) 'description': description,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    required String slug,
    required String type,
    required String reference,
    required String credit,
    String? lien,
    String? description,
    DateTime? createdAt,
  }) {
    return _generateMap(
      id: id,
      slug: slug,
      type: type,
      reference: reference,
      credit: credit,
      lien: lien,
      description: description,
      createdAt: createdAt,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? slug,
    String? type,
    String? reference,
    String? credit,
    String? lien,
    String? description,
    DateTime? createdAt,
  }) {
    return _generateMap(
      id: id,
      slug: slug,
      type: type,
      reference: reference,
      credit: credit,
      lien: lien,
      description: description,
      createdAt: createdAt,
    );
  }

  factory SourceDocumentaire.fromJson(Map<String, dynamic> jsonn) {
    return SourceDocumentaire(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      slug: jsonn['slug'] != null ? jsonn['slug'].toString() : '',
      type: jsonn['type'] != null ? jsonn['type'].toString() : '',
      reference: jsonn['reference'] != null
          ? jsonn['reference'].toString()
          : '',
      credit: jsonn['credit'] != null ? jsonn['credit'].toString() : '',
      lien: jsonn['lien'] != null ? jsonn['lien'].toString() : null,
      description: jsonn['description'] != null
          ? jsonn['description'].toString()
          : null,
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
    );
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      slug: slug,
      type: type,
      reference: reference,
      credit: credit,
      lien: lien,
      description: description,
      createdAt: createdAt,
    );
  }
}

class MembreEquipe implements SupadartClass<MembreEquipe> {
  final String compteId;
  final ROLE_EQUIPE role;
  final DateTime createdAt;

  const MembreEquipe({
    required this.compteId,
    required this.role,
    required this.createdAt,
  });

  static String get table_name => 'membre_equipe';
  static String get c_compteId => 'compte_id';
  static String get c_role => 'role';
  static String get c_createdAt => 'created_at';

  static List<MembreEquipe> converter(List<Map<String, dynamic>> data) {
    return data.map(MembreEquipe.fromJson).toList();
  }

  static MembreEquipe converterSingle(Map<String, dynamic> data) {
    return MembreEquipe.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? compteId,
    ROLE_EQUIPE? role,
    DateTime? createdAt,
  }) {
    return {
      if (compteId != null) 'compte_id': compteId,
      if (role != null) 'role': role.toString().split('.').last,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
    };
  }

  static Map<String, dynamic> insert({
    String? compteId,
    required ROLE_EQUIPE role,
    DateTime? createdAt,
  }) {
    return _generateMap(compteId: compteId, role: role, createdAt: createdAt);
  }

  static Map<String, dynamic> update({
    String? compteId,
    ROLE_EQUIPE? role,
    DateTime? createdAt,
  }) {
    return _generateMap(compteId: compteId, role: role, createdAt: createdAt);
  }

  factory MembreEquipe.fromJson(Map<String, dynamic> jsonn) {
    return MembreEquipe(
      compteId: jsonn['compte_id'] != null ? jsonn['compte_id'].toString() : '',
      role: jsonn['role'] != null
          ? ROLE_EQUIPE.values.byName(jsonn['role'].toString())
          : ROLE_EQUIPE.values.first,
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
    );
  }

  Map<String, dynamic> toJson() {
    return _generateMap(compteId: compteId, role: role, createdAt: createdAt);
  }
}

class TraceValidation implements SupadartClass<TraceValidation> {
  final String id;
  final String pinId;
  final String validateur;
  final String decision;
  final String typeDeValidation;
  final String? motif;
  final DateTime horodatage;

  const TraceValidation({
    required this.id,
    required this.pinId,
    required this.validateur,
    required this.decision,
    required this.typeDeValidation,
    this.motif,
    required this.horodatage,
  });

  static String get table_name => 'trace_validation';
  static String get c_id => 'id';
  static String get c_pinId => 'pin_id';
  static String get c_validateur => 'validateur';
  static String get c_decision => 'decision';
  static String get c_typeDeValidation => 'type_de_validation';
  static String get c_motif => 'motif';
  static String get c_horodatage => 'horodatage';

  static List<TraceValidation> converter(List<Map<String, dynamic>> data) {
    return data.map(TraceValidation.fromJson).toList();
  }

  static TraceValidation converterSingle(Map<String, dynamic> data) {
    return TraceValidation.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? pinId,
    String? validateur,
    String? decision,
    String? typeDeValidation,
    String? motif,
    DateTime? horodatage,
  }) {
    return {
      if (id != null) 'id': id,
      if (pinId != null) 'pin_id': pinId,
      if (validateur != null) 'validateur': validateur,
      if (decision != null) 'decision': decision,
      if (typeDeValidation != null) 'type_de_validation': typeDeValidation,
      if (motif != null) 'motif': motif,
      if (horodatage != null)
        'horodatage': horodatage.toUtc().toIso8601String(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    required String pinId,
    required String validateur,
    required String decision,
    required String typeDeValidation,
    String? motif,
    DateTime? horodatage,
  }) {
    return _generateMap(
      id: id,
      pinId: pinId,
      validateur: validateur,
      decision: decision,
      typeDeValidation: typeDeValidation,
      motif: motif,
      horodatage: horodatage,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? pinId,
    String? validateur,
    String? decision,
    String? typeDeValidation,
    String? motif,
    DateTime? horodatage,
  }) {
    return _generateMap(
      id: id,
      pinId: pinId,
      validateur: validateur,
      decision: decision,
      typeDeValidation: typeDeValidation,
      motif: motif,
      horodatage: horodatage,
    );
  }

  factory TraceValidation.fromJson(Map<String, dynamic> jsonn) {
    return TraceValidation(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      pinId: jsonn['pin_id'] != null ? jsonn['pin_id'].toString() : '',
      validateur: jsonn['validateur'] != null
          ? jsonn['validateur'].toString()
          : '',
      decision: jsonn['decision'] != null ? jsonn['decision'].toString() : '',
      typeDeValidation: jsonn['type_de_validation'] != null
          ? jsonn['type_de_validation'].toString()
          : '',
      motif: jsonn['motif'] != null ? jsonn['motif'].toString() : null,
      horodatage: jsonn['horodatage'] != null
          ? DateTime.parse(jsonn['horodatage'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
    );
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      pinId: pinId,
      validateur: validateur,
      decision: decision,
      typeDeValidation: typeDeValidation,
      motif: motif,
      horodatage: horodatage,
    );
  }
}

class Epoque implements SupadartClass<Epoque> {
  final String id;
  final String slug;
  final String libelle;
  final int borneDebut;
  final int borneFin;
  final int ordre;
  final DateTime createdAt;

  const Epoque({
    required this.id,
    required this.slug,
    required this.libelle,
    required this.borneDebut,
    required this.borneFin,
    required this.ordre,
    required this.createdAt,
  });

  static String get table_name => 'epoque';
  static String get c_id => 'id';
  static String get c_slug => 'slug';
  static String get c_libelle => 'libelle';
  static String get c_borneDebut => 'borne_debut';
  static String get c_borneFin => 'borne_fin';
  static String get c_ordre => 'ordre';
  static String get c_createdAt => 'created_at';

  static List<Epoque> converter(List<Map<String, dynamic>> data) {
    return data.map(Epoque.fromJson).toList();
  }

  static Epoque converterSingle(Map<String, dynamic> data) {
    return Epoque.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? slug,
    String? libelle,
    int? borneDebut,
    int? borneFin,
    int? ordre,
    DateTime? createdAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (slug != null) 'slug': slug,
      if (libelle != null) 'libelle': libelle,
      if (borneDebut != null) 'borne_debut': borneDebut,
      if (borneFin != null) 'borne_fin': borneFin,
      if (ordre != null) 'ordre': ordre,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    required String slug,
    required String libelle,
    required int borneDebut,
    required int borneFin,
    required int ordre,
    DateTime? createdAt,
  }) {
    return _generateMap(
      id: id,
      slug: slug,
      libelle: libelle,
      borneDebut: borneDebut,
      borneFin: borneFin,
      ordre: ordre,
      createdAt: createdAt,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? slug,
    String? libelle,
    int? borneDebut,
    int? borneFin,
    int? ordre,
    DateTime? createdAt,
  }) {
    return _generateMap(
      id: id,
      slug: slug,
      libelle: libelle,
      borneDebut: borneDebut,
      borneFin: borneFin,
      ordre: ordre,
      createdAt: createdAt,
    );
  }

  factory Epoque.fromJson(Map<String, dynamic> jsonn) {
    return Epoque(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      slug: jsonn['slug'] != null ? jsonn['slug'].toString() : '',
      libelle: jsonn['libelle'] != null ? jsonn['libelle'].toString() : '',
      borneDebut: jsonn['borne_debut'] != null
          ? int.parse(jsonn['borne_debut'].toString())
          : 0,
      borneFin: jsonn['borne_fin'] != null
          ? int.parse(jsonn['borne_fin'].toString())
          : 0,
      ordre: jsonn['ordre'] != null ? int.parse(jsonn['ordre'].toString()) : 0,
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
    );
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      slug: slug,
      libelle: libelle,
      borneDebut: borneDebut,
      borneFin: borneFin,
      ordre: ordre,
      createdAt: createdAt,
    );
  }
}

class Categorie implements SupadartClass<Categorie> {
  final String id;
  final String slug;
  final String libelle;
  final String? description;
  final int ordre;
  final DateTime createdAt;

  const Categorie({
    required this.id,
    required this.slug,
    required this.libelle,
    this.description,
    required this.ordre,
    required this.createdAt,
  });

  static String get table_name => 'categorie';
  static String get c_id => 'id';
  static String get c_slug => 'slug';
  static String get c_libelle => 'libelle';
  static String get c_description => 'description';
  static String get c_ordre => 'ordre';
  static String get c_createdAt => 'created_at';

  static List<Categorie> converter(List<Map<String, dynamic>> data) {
    return data.map(Categorie.fromJson).toList();
  }

  static Categorie converterSingle(Map<String, dynamic> data) {
    return Categorie.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({
    String? id,
    String? slug,
    String? libelle,
    String? description,
    int? ordre,
    DateTime? createdAt,
  }) {
    return {
      if (id != null) 'id': id,
      if (slug != null) 'slug': slug,
      if (libelle != null) 'libelle': libelle,
      if (description != null) 'description': description,
      if (ordre != null) 'ordre': ordre,
      if (createdAt != null) 'created_at': createdAt.toUtc().toIso8601String(),
    };
  }

  static Map<String, dynamic> insert({
    String? id,
    required String slug,
    required String libelle,
    String? description,
    required int ordre,
    DateTime? createdAt,
  }) {
    return _generateMap(
      id: id,
      slug: slug,
      libelle: libelle,
      description: description,
      ordre: ordre,
      createdAt: createdAt,
    );
  }

  static Map<String, dynamic> update({
    String? id,
    String? slug,
    String? libelle,
    String? description,
    int? ordre,
    DateTime? createdAt,
  }) {
    return _generateMap(
      id: id,
      slug: slug,
      libelle: libelle,
      description: description,
      ordre: ordre,
      createdAt: createdAt,
    );
  }

  factory Categorie.fromJson(Map<String, dynamic> jsonn) {
    return Categorie(
      id: jsonn['id'] != null ? jsonn['id'].toString() : '',
      slug: jsonn['slug'] != null ? jsonn['slug'].toString() : '',
      libelle: jsonn['libelle'] != null ? jsonn['libelle'].toString() : '',
      description: jsonn['description'] != null
          ? jsonn['description'].toString()
          : null,
      ordre: jsonn['ordre'] != null ? int.parse(jsonn['ordre'].toString()) : 0,
      createdAt: jsonn['created_at'] != null
          ? DateTime.parse(jsonn['created_at'].toString())
          : DateTime.fromMillisecondsSinceEpoch(0),
    );
  }

  Map<String, dynamic> toJson() {
    return _generateMap(
      id: id,
      slug: slug,
      libelle: libelle,
      description: description,
      ordre: ordre,
      createdAt: createdAt,
    );
  }
}

class PinEpoque implements SupadartClass<PinEpoque> {
  final String pinId;
  final String epoqueId;

  const PinEpoque({required this.pinId, required this.epoqueId});

  static String get table_name => 'pin_epoque';
  static String get c_pinId => 'pin_id';
  static String get c_epoqueId => 'epoque_id';

  static List<PinEpoque> converter(List<Map<String, dynamic>> data) {
    return data.map(PinEpoque.fromJson).toList();
  }

  static PinEpoque converterSingle(Map<String, dynamic> data) {
    return PinEpoque.fromJson(data);
  }

  static Map<String, dynamic> _generateMap({String? pinId, String? epoqueId}) {
    return {
      if (pinId != null) 'pin_id': pinId,
      if (epoqueId != null) 'epoque_id': epoqueId,
    };
  }

  static Map<String, dynamic> insert({String? pinId, String? epoqueId}) {
    return _generateMap(pinId: pinId, epoqueId: epoqueId);
  }

  static Map<String, dynamic> update({String? pinId, String? epoqueId}) {
    return _generateMap(pinId: pinId, epoqueId: epoqueId);
  }

  factory PinEpoque.fromJson(Map<String, dynamic> jsonn) {
    return PinEpoque(
      pinId: jsonn['pin_id'] != null ? jsonn['pin_id'].toString() : '',
      epoqueId: jsonn['epoque_id'] != null ? jsonn['epoque_id'].toString() : '',
    );
  }

  Map<String, dynamic> toJson() {
    return _generateMap(pinId: pinId, epoqueId: epoqueId);
  }
}
